version: '3.10'
services:
  mongo_db:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - marynjuguna1-network
    volumes:
      - mongo_db:/data/db

  
  backend:
    container_name: yolo_backend_container
    image: marynjuguna1/yolo_backend:v1.1
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongo_db
  
    networks:
      - marynjuguna1-network

  client:
    container_name: yolo_client_container
    image: marynjuguna1/yolo_client:v1.1
    build:
      context: client
      dockerfile: Dockerfile
    
    ports:
      - '3000:3000'
 
    depends_on:
      - backend
    networks:
      - marynjuguna1-network
    stdin_open: true
    tty: true

networks:
      marynjuguna1-network:
        driver: bridge
volumes:
      mongo_db: {}    