version: "3.8"
services:
  backend:
    build: ./backend
    container_name: yolo_backend_c
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/backend
  client:
    build: ./client
    container_name: yolo_client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app