version: '3.11'
services:
  
  client:
    tty: true
    build:
      context: .
      dockerfile: client.Dockerfile
    image: marynjuguna1/yolo_client:v1.1
    container_name: yolo_client_container
    ports:
      - '3000:3000'
    networks:
      - marynjuguna1-network
    depends_on:
      - backend
    
    
  backend:
    
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: marynjuguna1/yolo_backend:v1.1
    container_name: backend_container
    ports:
      - '5000:5000'
    networks:
      - marynjuguna1-network
    depends_on:
      - mongo_db
    
  mongo_db:
    container_name: mongodb
    image: mongo
    volumes:
      - mongo_db:/data/db 
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      
    networks:
      - marynjuguna1-network
    

networks:
      marynjuguna1-network:
        driver: bridge
volumes:
      mongo_db: {}    