version: "3.8"
services:
  backend:
    build: ./backend
    image: marynjuguna1/yolo_backend:v1.1
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/backend
  client:
    build: ./client
    image: marynjuguna1/yolo_client:v1.1
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true