---
- name: Install Docker pre-requisites 
  hosts: all
  become: true

  roles:
    - update-packages
    - install-pre-requisites
    - dir-Docker-GPG
    - download-Docker-GPG
    - Docker-sources
    - Install-Docker-Engine
    - deploy-yolo-app
    



  

    




  