---
- name: Install Docker pre-requisites 
  hosts: all
  become: true

  roles:
    - update-packages
    - install-docker-engine
    - start-docker-service
    - Install-pip3
    - Install-Docker
    - deploy-yolo-app
    



  

    




  