---
- name: Deploy Docker Compose services
  hosts: localhost
  become: yes
  tasks:
    - name: Copy Docker Compose file
      copy:
        src: /path/to/docker-compose.yml
        dest: /path/on/remote/docker-compose.yml

    - name: Ensure Docker Compose is installed
      package:
        name: docker-compose
        state: present

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /path/on/remote/
