apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-service
  namespace: yolo-ecommerce
spec:
  type: LoadBalancer
  selector:
    app: yolo-backend
  ports:
    - protocol: TCP
      port: 5000 # Can be same as container port
      targetPort: 5000
