apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  labels:
    app: yolo-backend
  namespace: yolo-ecommerce
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      # Add the containers property with details
      containers:
      - name: yolo-backend  # Match container name
        image: marynjuguna1/yolo_backend:v1.1
        imagePullPolicy: Always
        env:
            - name: MONGODB_URI
              value: mongodb://mongo-db:27017/yolomy
        ports:
          - containerPort: 5000
        resources:
          requests:
            cpu: 200m # Request 200 millicores (adjust based on your needs)
            memory: 512Mi # Request 512 Megabytes (adjust based on your needs)
          limits:
            cpu: 1000m # Limit to 1 core (adjust based on your needs)
            memory: 1.5Gi # Limit to 1.5 Gigabytes (adjust based on your needs)
  