apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  labels:
    app: yolo-backend
  namespace: yolo-ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      # Add the containers property with details
      containers:
      - name: yolo-backend  
        image: marynjuguna1/yolo_backend:v1.1
        imagePullPolicy: Always
        
        ports:
          - containerPort: 5000
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: 200m 
            memory: 512Mi 
          limits:
            cpu: 1000m 
            memory: 1.5Gi 

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-backend
spec:
  selector:
    app: yolo-backend
  ports:
  - port: 5000
    targetPort: 5000