apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client
  labels:
    app: yolo-client
  namespace: yolo-ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
      - name: yolo-client
        image: marynjuguna1/yolo_client:v1.1
        imagePullPolicy: Always 

        ports:
          - containerPort: 3000
        resources:
          requests:
            cpu: 100m 
            memory: 256Mi 
          limits:
            cpu: 500m 
            memory: 0.25Gi 
