apiVersion: v1
kind: Service
metadata:
  name: yolo-client-service
  namespace: yolo-ecommerce
spec:
  selector:
    app: yolo-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer # Adjust type as needed (e.g., NodePort)
