apiVersion: "v1"
kind: "Service"
metadata: 
  name: "mongo-db"
  namespace: yolo-ecommerce
  labels: 
    app: "mongo-db"
spec:
  selector: 
    app: "mongo-db" 
  ports: 
    - protocol: TCP
      port: 27017
      targetPort: 27017
  